name: Build SDR++ Windows Dev

on:
  workflow_dispatch:
  push:
    branches:
      - master

env:
  BUILD_TYPE: Release

jobs:
  build_windows_dev:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create build directory
        shell: pwsh
        run: cmake -E make_directory ${{ runner.workspace }}/build

      - name: Download PothosSDR
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri "https://downloads.myriadrf.org/builds/PothosSDR/PothosSDR-2020.01.26-vc14-x64.exe" -OutFile ${{ runner.workspace }}/pothos.exe
          mkdir "C:/Program Files/PothosSDR"
          7z x ${{ runner.workspace }}/pothos.exe -o"C:/Program Files/PothosSDR/"

      - name: Download libusb
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri "https://github.com/libusb/libusb/releases/download/v1.0.23/libusb-1.0.23.7z" -OutFile ${{ runner.workspace }}/libusb.7z
          7z x ${{ runner.workspace }}/libusb.7z -o${{ runner.workspace }}/libusb_old
          Remove-Item "C:/Program Files/PothosSDR/bin/libusb-1.0.dll"
          Copy-Item "${{ runner.workspace }}/libusb_old/MS64/dll/libusb-1.0.dll" "C:/Program Files/PothosSDR/bin/"
          Remove-Item "C:/Program Files/PothosSDR/lib/libusb-1.0.lib"
          Copy-Item "${{ runner.workspace }}/libusb_old/MS64/dll/libusb-1.0.lib" "C:/Program Files/PothosSDR/lib/"

      - name: Download librtlsdr
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri "https://ftp.osmocom.org/binaries/windows/rtl-sdr/rtl-sdr-64bit-20240623.zip" -OutFile ${{ runner.workspace }}/rtl-sdr.zip
          7z x ${{ runner.workspace }}/rtl-sdr.zip -o${{ runner.workspace }}/rtl-sdr
          Remove-Item "C:/Program Files/PothosSDR/bin/rtlsdr.dll"
          Copy-Item "${{ runner.workspace }}/rtl-sdr/rtl-sdr-64bit-20240623/librtlsdr.dll" "C:/Program Files/PothosSDR/bin/rtlsdr.dll"

      - name: Prepare MinGW
        shell: pwsh
        run: |
          C:/msys64/msys2_shell.cmd -defterm -here -no-start -mingw64 -c "pacman --noconfirm -Syu --needed base-devel mingw-w64-x86_64-toolchain mingw-w64-x86_64-cmake mingw-w64-x86_64-ninja"
          C:/msys64/msys2_shell.cmd -defterm -here -no-start -mingw64 -c "pacman --noconfirm -S --needed mingw-w64-x86_64-fftw mingw-w64-x86_64-glfw mingw-w64-x86_64-zstd mingw-w64-x86_64-libusb mingw-w64-x86_64-portaudio mingw-w64-x86_64-rtaudio mingw-w64-x86_64-spdlog"

      - name: Configure
        working-directory: ${{ runner.workspace }}/build
        shell: pwsh
        run: |
          C:/msys64/msys2_shell.cmd -defterm -here -no-start -mingw64 -c "cmake -G Ninja /c/${env:GITHUB_WORKSPACE.Substring(3)} -DCMAKE_BUILD_TYPE=Release -DOPT_BUILD_AIRSPY_SOURCE=OFF -DOPT_BUILD_AIRSPYHF_SOURCE=OFF -DOPT_BUILD_AUDIO_SOURCE=OFF -DOPT_BUILD_HACKRF_SOURCE=OFF -DOPT_BUILD_PLUTOSDR_SOURCE=OFF -DOPT_BUILD_RTL_SDR_SOURCE=ON -DOPT_BUILD_RTL_TCP_SOURCE=ON -DOPT_BUILD_AUDIO_SINK=ON -DOPT_BUILD_NETWORK_SINK=ON -DOPT_BUILD_ATV_DECODER=OFF -DOPT_BUILD_METEOR_DEMODULATOR=OFF -DOPT_BUILD_PAGER_DECODER=OFF -DOPT_BUILD_DISCORD_PRESENCE=OFF"

      - name: Build
        working-directory: ${{ runner.workspace }}/build
        shell: pwsh
        run: |
          C:/msys64/msys2_shell.cmd -defterm -here -no-start -mingw64 -c "cmake --build . --parallel"

      - name: Package
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path ${{ runner.workspace }}/sdrpp_windows_dev/root | Out-Null
          New-Item -ItemType Directory -Force -Path ${{ runner.workspace }}/sdrpp_windows_dev/modules | Out-Null
          Copy-Item -Recurse root/* ${{ runner.workspace }}/sdrpp_windows_dev/root/
          Copy-Item ${{ runner.workspace }}/build/sdrpp.exe ${{ runner.workspace }}/sdrpp_windows_dev/
          Get-ChildItem -Recurse -Filter *.dll ${{ runner.workspace }}/build | ForEach-Object { Copy-Item $_.FullName ${{ runner.workspace }}/sdrpp_windows_dev/modules/ }
          Compress-Archive -Path ${{ runner.workspace }}/sdrpp_windows_dev/* -DestinationPath ${{ runner.workspace }}/sdrpp_windows_dev.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: sdrpp_windows_dev
          path: ${{ runner.workspace }}/sdrpp_windows_dev.zip
